version: '3'

services:
    # Laravel Application
    app:
        image: composer:latest
        volumes:
            - ./laravel:/var/www
        working_dir: /var/www
        command: create-project laravel/laravel .

    # MySQL Database
    db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./mysql/data:/var/lib/mysql

    # PHP-FPM Service
    php-fpm:
        build:
            context: .
            dockerfile: ./php-fpm/Dockerfile
        volumes:
            - ./laravel:/var/www
        depends_on:
            - db

    # Nginx Service
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./laravel:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
